src/java/br/uem/din/trabalho/bean/BeneficiarioBean.java
package br.uem.din.trabalho.bean;

import br.uem.din.trabalho.controller.BeneficiarioController;
import br.uem.din.trabalho.controller.ProjetoController;
import br.uem.din.trabalho.model.Beneficiario;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import javax.faces.bean.ManagedBean;
import org.primefaces.component.dialog.Dialog;

@ManagedBean(name = "beneficiarioBean")
@SessionScoped
public class BeneficiarioBean implements Serializable {

    private String nome;
    private String cpf;
    private String matricula;
    private String email;
    private String internoUEM;
    private BigDecimal cargaHoraria;
    private BigDecimal frequencia;
    private BigDecimal nota;
    private Dialog alerta1;
    private Dialog alerta2;

    public BeneficiarioBean() {
    }

    /*CADASTRO*/
    public String cadastrar() {
        verificarExt();
        if (this.cpf.equals("") || this.cpf == null) {
            this.alerta2.setVisible(true);
            return "beneficiario";
        }
        if (!BeneficiarioController.getInstance().validarBeneficiario(this.cpf)) {
            this.alerta1.setVisible(false);
            BeneficiarioController.getInstance().salvarBeneficiario(new Beneficiario(frequencia, nota, nome, cpf, matricula, email, internoUEM, cargaHoraria, ProjetoController.getInstance().listarProjetoSelecionado().get(0)));
            return "beneficiario";
        } else {
            this.alerta1.setVisible(true);
            return "beneficiario";
        }
    }

    public void verificarExt() {
        if (this.getInternoUEM().equals("Comunidade Externa")) {
            this.setMatricula("Não possui");
        }
    }

    /*DELETE*/
    public String deletar(String cpf) {
        BeneficiarioController.getInstance().deletarBeneficiario(cpf);
        return "beneficiario";
    }

    public String deletarLista(String cpf) {
        BeneficiarioController.getInstance().deletarBeneficiario(cpf);
        return "lista";
    }

    /*LISTAGEM*/
    public List<Beneficiario> getBeneficiarios() {
        return BeneficiarioController.getInstance().listarBeneficiarios();
    }

    /*GET & SETS*/
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public String getMatricula() {
        return matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getInternoUEM() {
        return internoUEM;
    }

    public void setInternoUEM(String internoUEM) {
        this.internoUEM = internoUEM;
    }

    public Dialog getAlerta1() {
        return alerta1;
    }

    public void setAlerta1(Dialog alerta1) {
        this.alerta1 = alerta1;
    }

    public Dialog getAlerta2() {
        return alerta2;
    }

    public void setAlerta2(Dialog alerta2) {
        this.alerta2 = alerta2;
    }

    public BigDecimal getCargaHoraria() {
        return cargaHoraria;
    }

    public void setCargaHoraria(BigDecimal cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }

    public BigDecimal getFrequencia() {
        return frequencia;
    }

    public void setFrequencia(BigDecimal frequencia) {
        this.frequencia = frequencia;
    }

    public BigDecimal getNota() {
        return nota;
    }

    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }

}

src/java/br/uem/din/trabalho/bean/ParticipanteBean.java
package br.uem.din.trabalho.bean;

import br.uem.din.trabalho.controller.ParticipanteController;
import br.uem.din.trabalho.controller.ProjetoController;
import br.uem.din.trabalho.model.Participante;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import javax.faces.bean.ManagedBean;
import org.primefaces.component.dialog.Dialog;

@ManagedBean(name = "participanteBean")
@SessionScoped
public class ParticipanteBean implements Serializable {

    private String nome;
    private String cpf;
    private String matricula;
    private String email;
    private String internoUEM;
    private BigDecimal cargaHoraria;
    private String curso;
    private String tipoAtuacao;
    private Dialog alerta1;
    private Dialog alerta2;

    public ParticipanteBean() {
    }

    /*CADASTRO*/
    public String cadastrar() {
        verificarExt();
        if (this.cpf.equals("") || this.cpf == null) {
            this.alerta2.setVisible(true);
            return "participante";
        }
        if (!ParticipanteController.getInstance().verificarParticipante(this.cpf)) {
            this.alerta1.setVisible(false);
            ParticipanteController.getInstance().salvarParticipante(new Participante(curso, tipoAtuacao, nome, cpf, matricula, email, internoUEM, cargaHoraria, ProjetoController.getInstance().listarProjetoSelecionado().get(0)));
            return "participante";
        } else {
            this.alerta1.setVisible(true);
            return "participante";
        }
    }

    public void verificarExt() {
        if (this.getInternoUEM().equals("Comunidade Externa")) {
            this.setCurso("Não possui");
            this.setMatricula("Não possui");
        }
    }

    /*DELETE*/
    public String deletar(String cpf) {
        ParticipanteController.getInstance().deletarParticipante(cpf);
        return "participante";
    }

    public String deletarLista(String cpf) {
        ParticipanteController.getInstance().deletarParticipante(cpf);
        return "lista";
    }

    /*LISTAGEM*/
    public List<Participante> getParticipantes() {
        return ParticipanteController.getInstance().listarPaticipantes();
    }

    /*DEFINIR CARGA HORÁRIA*/
//    public void somaCargaHoraria(int cargaHorariaTema) {
//        if (this.checkboxTema.isSelected()) {
//            this.setCargaHoraria(this.getCargaHoraria() + cargaHorariaTema);
//        } else {
//            this.setCargaHoraria(this.getCargaHoraria() - cargaHorariaTema);
//        }
//    }

    /* GET & SETS*/
    public String getNome() {
        return nome;
    }

    public String getCurso() {
        return curso;
    }

    public void setCurso(String curso) {
        this.curso = curso;
    }

    public String getTipoAtuacao() {
        return tipoAtuacao;
    }

    public void setTipoAtuacao(String tipoAtuacao) {
        this.tipoAtuacao = tipoAtuacao;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public String getMatricula() {
        return matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getInternoUEM() {
        return internoUEM;
    }

    public void setInternoUEM(String internoUEM) {
        this.internoUEM = internoUEM;
    }

    public Dialog getAlerta1() {
        return alerta1;
    }

    public void setAlerta1(Dialog alerta1) {
        this.alerta1 = alerta1;
    }

    public Dialog getAlerta2() {
        return alerta2;
    }

    public void setAlerta2(Dialog alerta2) {
        this.alerta2 = alerta2;
    }

    public BigDecimal getCargaHoraria() {
        return cargaHoraria;
    }

    public void setCargaHoraria(BigDecimal cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
}

src/java/br/uem/din/trabalho/bean/ProjetoListagemBean.java
package br.uem.din.trabalho.bean;

import br.uem.din.trabalho.controller.ProjetoController;
import br.uem.din.trabalho.model.Programacao;
import br.uem.din.trabalho.model.Projeto;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;

@ManagedBean(name = "projetoListagemBean")
@SessionScoped
public class ProjetoListagemBean implements Serializable {

    public ProjetoListagemBean() {
    }

    public List<Projeto> getProjetos() {
        return ProjetoController.getInstance().listarProjetos();
    }

    public Projeto getProjeto(String ano, String nuProcesso) {
        return ProjetoController.getInstance().getProjeto(ano, nuProcesso);
    }

    public List<Projeto> getProjetoSelecionado() {
        return ProjetoController.getInstance().listarProjetoSelecionado();
    }

    public List<Programacao> getProgramacao() {
        return ProjetoController.getInstance().listarProgramacao();
    }
}

src/java/br/uem/din/trabalho/bean/loginBean.java
package br.uem.din.trabalho.bean;

import br.uem.din.trabalho.controller.ProjetoController;
import br.uem.din.trabalho.controller.UsuarioController;
import br.uem.din.trabalho.model.Beneficiario;
import br.uem.din.trabalho.model.Participante;
import br.uem.din.trabalho.model.Pessoa;
import br.uem.din.trabalho.model.Programacao;
import br.uem.din.trabalho.model.Projeto;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;

@ManagedBean(name = "loginBean")
@SessionScoped
public class loginBean implements Serializable {

    private String login;
    private String senha;

    public loginBean() {
    }

    public Pessoa getSessaoUsuario() {
        return UsuarioController.getInstance().mostrarUsuario();
    }

    public String autenticar() {
        preencherProjetos();
        String email = getLogin() + "@uem.br";
        Pessoa pessoa = new Pessoa("", "", getLogin(), email, "", BigDecimal.ZERO, null);
        UsuarioController.getInstance().salvarUsuario(pessoa);
        return "menu";
    }

    private void preencherProjetos() {
        Programacao prog1 = new Programacao("Teste1", 12);
        Programacao prog2 = new Programacao("Teste2", 43);
        Programacao prog3 = new Programacao("Teste3", 35);
        Programacao prog4 = new Programacao("Teste4", 75);
        Programacao prog5 = new Programacao("Teste5", 25);
        Programacao prog6 = new Programacao("Teste6", 52);
        List<Programacao> lista1 = new ArrayList<>();
        List<Programacao> lista2 = new ArrayList<>();
        List<Programacao> lista3 = new ArrayList<>();

        List<Participante> participante1 = new ArrayList<>();
        List<Participante> participante2 = new ArrayList<>();
        List<Participante> participante3 = new ArrayList<>();

        List<Beneficiario> beneficiario1 = new ArrayList<>();
        List<Beneficiario> beneficiario2 = new ArrayList<>();
        List<Beneficiario> beneficiario3 = new ArrayList<>();

        lista1.add(prog1);
        lista1.add(prog3);
        lista1.add(prog5);

        lista2.add(prog6);
        lista2.add(prog4);
        lista2.add(prog2);

        lista3.add(prog2);
        lista3.add(prog1);
        lista3.add(prog5);

        Projeto projeto1 = new Projeto("Curso de iniciação cientifica", "5682", "2018", lista1, participante1, beneficiario1);
        Projeto projeto2 = new Projeto("Evento de solidificação da Água", "4724", "2019", lista2, participante2, beneficiario2);
        Projeto projeto3 = new Projeto("Curso para Realizar Macarrão Instantâneo", "7235", "2019", lista3, participante3, beneficiario3);
        ProjetoController.getInstance().salvarProjeto(projeto1);
        ProjetoController.getInstance().salvarProjeto(projeto2);
        ProjetoController.getInstance().salvarProjeto(projeto3);
    }

    /*GETS & SETS*/
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
}

src/java/br/uem/din/trabalho/model/Beneficiario.java
package br.uem.din.trabalho.model;

import java.math.BigDecimal;

public class Beneficiario extends Pessoa {

    private BigDecimal frequencia;
    private BigDecimal nota;

    public Beneficiario(BigDecimal frequencia, BigDecimal nota, String nome, String cpf, String matricula, String email, String internoUEM, BigDecimal cargaHoraria, Projeto projeto) {
        super(nome, cpf, matricula, email, internoUEM, cargaHoraria, projeto);
        this.frequencia = frequencia;
        this.nota = nota;
    }


    public Beneficiario() {
    }

    public BigDecimal getFrequencia() {
        return frequencia;
    }

    public void setFrequencia(BigDecimal frequencia) {
        this.frequencia = frequencia;
    }

    public BigDecimal getNota() {
        return nota;
    }

    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }


}

src/java/br/uem/din/trabalho/controller/BeneficiarioController.java
package br.uem.din.trabalho.controller;

import br.uem.din.trabalho.model.Beneficiario;
import java.util.List;

public class BeneficiarioController {

    private static BeneficiarioController instance;

    private BeneficiarioController() {
    }

    public static BeneficiarioController getInstance() {
        if (instance == null) {
            instance = new BeneficiarioController();
        }
        return instance;
    }

    public void salvarBeneficiario(Beneficiario beneficiario) {
        ProjetoController.getInstance().listarProjetoSelecionado().get(0).getBeneficiarios().add(beneficiario);
    }

    public List<Beneficiario> listarBeneficiarios() {
        return ProjetoController.getInstance().listarProjetoSelecionado().get(0).getBeneficiarios();
    }

    public boolean deletarBeneficiario(String cpf) {
        boolean removed = false;
        List<Beneficiario> beneficiarios;
        beneficiarios = ProjetoController.getInstance().listarProjetoSelecionado().get(0).getBeneficiarios();
        for (int x = 0; x < beneficiarios.size(); x++) {
            if (beneficiarios.get(x).getCpf().equals(cpf)) {
                removed = beneficiarios.remove(beneficiarios.get(x));
            }
        }
        ProjetoController.getInstance().listarProjetoSelecionado().get(0).setBeneficiarios(beneficiarios);
        return removed;
    }

    public boolean validarBeneficiario(String cpf) {
        boolean existe = false;
        List<Beneficiario> beneficiarios;
        beneficiarios = ProjetoController.getInstance().listarProjetoSelecionado().get(0).getBeneficiarios();
        for (int x = 0; x < beneficiarios.size(); x++) {
            if (beneficiarios.get(x).getCpf().equals(cpf)) {
                existe = true;
            }
        }
        return existe;
    }
}

src/java/br/uem/din/trabalho/controller/ParticipanteController.java
package br.uem.din.trabalho.controller;

import br.uem.din.trabalho.model.Participante;
import java.util.List;

public class ParticipanteController {

    private static ParticipanteController instance;

    private ParticipanteController() {
    }

    public static ParticipanteController getInstance() {
        if (instance == null) {
            instance = new ParticipanteController();
        }
        return instance;
    }

    public void salvarParticipante(Participante participante) {
        ProjetoController.getInstance().listarProjetoSelecionado().get(0).getParticipantes().add(participante);
    }

    public List<Participante> listarPaticipantes() {
        return ProjetoController.getInstance().listarProjetoSelecionado().get(0).getParticipantes();
    }

    public boolean deletarParticipante(String cpf) {
        boolean removed = false;
        List<Participante> participantes;
        participantes = ProjetoController.getInstance().listarProjetoSelecionado().get(0).getParticipantes();

        for (int x = 0; x < participantes.size(); x++) {
            if (participantes.get(x).getCpf().equals(cpf)) {
                removed = participantes.remove(participantes.get(x));
            }
        }
        ProjetoController.getInstance().listarProjetoSelecionado().get(0).setParticipantes(participantes);
        return removed;
    }

    public boolean verificarParticipante(String cpf) {
        boolean existe = false;
        List<Participante> participantes;
        participantes = ProjetoController.getInstance().listarProjetoSelecionado().get(0).getParticipantes();
        for (int x = 0; x < participantes.size(); x++) {
            if (participantes.get(x).getCpf().equals(cpf)) {
                existe = true;
            }
        }
        return existe;
    }
}

web/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<xhtml xmlns="http://www.w3.org/1999/xhtml"
       xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>header</title>
        <link rel="stylesheet" type="text/css" href="header.css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:form>
            <div class="banner" style="background-image: url(imagens/fundo1.jpg); 
                 background-size:100% 100%; background-repeat:no-repeat;">
                <div class="logo-uem">
                    <a href="http://www.uem.br/">
                        <image src="/imagens/logouembrancocomsombra.png"/>
                    </a>
                </div>
                <div class="texto-logo">
                    <div sclass="texto-portal">SISTEMA DE GESTÃO</div>
                    <div sclass="texto-portal">PARTICIPANTES E BENEFICIÁRIOS</div>
                </div>
                <div class="logo-pr">
                    <a href="http://www.pr.gov.br/">
                        <image src="/imagens/bandeira-governo-PR.png"/>
                    </a>
                </div>
            </div>
            <div align="right" style="background-color: #c39bf7">
                <h:dataTable value="#{loginBean.sessaoUsuario}" var="sessao"
                             styleClass="order-table"
                             headerClass="order-table-header"
                             rowClasses="order-table-odd-row,order-table-even-row"

                             >
                    <h:column>
                        <div class="sessao">
                            <h1 class="h1">Sessão:</h1>
                            <h2 class="h2">#{sessao.email}</h2>
                        </div>
                    </h:column>
                </h:dataTable>
            </div>
        </h:form>
    </h:body>
</xhtml>

web/participante.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<xhtml xmlns="http://www.w3.org/1999/xhtml"
       xmlns:h="http://xmlns.jcp.org/jsf/html"
       xmlns:f="http://xmlns.jcp.org/jsf/core"
       xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
       xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>SGPB</title>
        <link rel="stylesheet" type="text/css" href="estilo.css" />
        <script type="text/javascript" src="js/javascript.js"/>
    </h:head>
    <h:body>
        <div class="fundo">
            <div>
                <ui:include src="header.xhtml"></ui:include>
                <center>
                    <div>
                        <div class="fundoMenuBar">
                            <h:form>
                                <div>
                                    <menubar>                                        
                                        <menuitem class="buttonMenuBar"><h:commandButton class="buttonMenuBar" style="width: auto" action="#{menuBean.hrefMenu()}" value="Menu"></h:commandButton></menuitem>
                                        <a href="menuProjeto.xhtml"><menuitem class="buttonMenuBar">Voltar</menuitem></a>
                                        <menuitem class="buttonMenuBar"><h:commandButton class="buttonMenuBar" style="width: auto" action="#{menuBean.hrefLogin()}" value="Sair"></h:commandButton></menuitem>
                                    </menubar>
                                </div>
                            </h:form>
                        </div>
                    </div>
                    <div align="center" style="background-color: #8e61cc">
                        <h:dataTable value="#{projetoListagemBean.projetoSelecionado}" var="projeto"
                                     styleClass="order-table"
                                     headerClass="order-table-header"
                                     rowClasses="order-table-odd-row,order-table-even-row"
                                     >
                            <h:column>
                                <h1 class="tituloProj">Titulo: <a class="tituloProj" >#{projeto.titulo}</a></h1>
                            </h:column>
                            <h:column>
                                <h1 class="tituloProj" >Ano/Numero do Processo: <a class="tituloProj" >#{projeto.ano}</a> / <a class="tituloProj" >#{projeto.nuProcesso}</a></h1>
                            </h:column>
                        </h:dataTable>
                    </div>
                </center>
            </div>
            <div align="center" class="fundo">
                <h1 class="titulo"> Cadastro de Participante </h1>
                <h:form>
                    <div class="fundoCadastro">
                        <div align="left">
                            <h:outputText value="Nome: "  class="rotulo" />
                            <h:inputText id="nome" title="Nome"
                                         value="#{participanteBean.nome}" class="campo" />
                        </div>
                        <div align="left">
                            <h:outputText value="CPF : "  class="rotulo" />
                            <h:inputText id="cpf" title="Somente Dígitos" maxlength="11" style="width: 100px" onblur="TestaCPF(this.value)"
                                         onkeypress="if(event.which &lt; 48 || event.which &gt; 57) return false;"
                                         value="#{participanteBean.cpf}" class="campo" /> <h:commandButton title="O Cpf precisa conter somente digitos" class="btnHelp" onclick="help()" value="?"></h:commandButton>
                        </div>
                        <div align="left">
                            <h:outputText value="E-mail : "  class="rotulo" />
                            <h:inputText id="email" title="email"
                                         value="#{participanteBean.email}" class="campo" />
                        </div>
                        <div align="left" id="rowMatricula">
                            <h:outputText value="Matricula : "  class="rotulo" />
                            <h:inputText id="matricula" title="Matricula" onkeypress="if(event.which &lt; 48 || event.which &gt; 57) return false;"
                                         maxlength="8" style="width: 60px" 
                                         value="#{participanteBean.matricula}" class="campo" />
                        </div>
                        <div align="left">
                            <h:outputText value="Carga Horária : "  class="rotulo" />
                            <h:inputText id="cargaHoraria" title="cargaHoraria" onkeypress="if(event.which &lt; 48 || event.which &gt; 57) return false;"
                                         value="#{participanteBean.cargaHoraria}" style="width: 28px" maxlength="3" class="campo" />
                        </div>
                        <div align="left">
                            <h:outputText value="Curso : "  class="rotulo" />
                            <h:inputText id="curso" title="Curso"
                                         value="#{participanteBean.curso}" class="campo" />
                        </div>
                        <div align="left">
                            <h:outputText value="Tipo de Atuação : " class="rotulo" />
                            <h:selectOneMenu value="#{participanteBean.tipoAtuacao}">
                                <f:selectItem itemValue="comissao" itemLabel="Comissão Organizadora" />
                                <f:selectItem itemValue="ministrante" itemLabel="Ministrante" />
                                <f:selectItem itemValue="monitor" itemLabel="Monitor" />
                                <f:selectItem itemValue="outros" itemLabel="Outros" />
                            </h:selectOneMenu>
                        </div>
                        <br/>
                        <div align="left">
                            <h:outputText value="Interno/Externo UEM : "  class="rotulo" />
                            <h:selectOneRadio value="#{participanteBean.internoUEM}">
                                <f:selectItem itemValue="Comunidade Interna" itemLabel="Comunidade Interna" />
                                <f:selectItem itemValue="Comunidade Externa" itemLabel="Comunidade Externa" />
                            </h:selectOneRadio>
                        </div>
                        <br/>
                        <div align="left">
                            <h:outputText value="Participação : " class="rotulo" />
                            <h:dataTable value="#{projetoListagemBean.programacao}" var="programacao"
                                         styleClass="order-table"
                                         headerClass="order-table-header"
                                         rowClasses="order-table-odd-row,order-table-even-row"
                                         >
                                <h:column>
                                    <h1 class="lista">#{programacao.nomeTema}<a class="lista">  CH: </a> <a class="lista" >#{programacao.cargaHorariaTema}</a><h:selectBooleanCheckbox onclick="calcularCargaHoraria(this,#{programacao.cargaHorariaTema})"></h:selectBooleanCheckbox></h1>
                                </h:column>
                            </h:dataTable>
                        </div>
                        <h:commandButton id="submit" value="Cadastrar" 
                                         action="#{participanteBean.cadastrar()}"  class="button" />
                    </div>
                </h:form>
            </div>
            <div class="fundo">
                <h:form>
                    <center>
                        <h1 class="titulo" align="center">Participantes Cadastrados</h1>
                    </center>
                    <br />
                    <br />
                    <div align="center" style="background-color: #8e61cc">
                        <h:dataTable value="#{participanteBean.participantes}" var="participante"
                                     styleClass="order-table"
                                     headerClass="order-table-header"
                                     rowClasses="order-table-odd-row,order-table-even-row"

                                     >
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader">Nome</h1>
                                </f:facet>
                                <h1 class="lista" >#{participante.nome}</h1>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader" >CPF</h1>
                                </f:facet>
                                <h1 class="lista" >#{participante.cpf}</h1>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader" >Email</h1>
                                </f:facet>
                                <h1 class="lista" >#{participante.email}</h1>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader" >Matricula</h1>
                                </f:facet>
                                <h1 class="lista" >#{participante.matricula}</h1>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader">Carga Horária</h1>
                                </f:facet>
                                <h1 class="lista" >#{participante.cargaHoraria}</h1>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader">Curso</h1>
                                </f:facet>
                                <h1 class="lista" >#{participante.curso}</h1>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader" >Tipo de Atuação</h1>
                                </f:facet>
                                <h1 class="lista" >#{participante.tipoAtuacao}</h1>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader" >Interno/Externo</h1>
                                </f:facet>
                                <h1 class="lista" >#{participante.internoUEM}</h1>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h1 class="listaHeader" >Excluir</h1>
                                </f:facet>
                                <h:commandButton value="Remover" style="background-color: #61349b; font-size: 10px; color: #FFFFFF; text-align: center;"
                                                 action="#{participanteBean.deletar(participante.cpf)}" />
                            </h:column>
                        </h:dataTable>
                    </div>
                </h:form>
            </div>
            <p:dialog id="alerta1" header="Erro!" binding="#{participanteBean.alerta1}" class="alerta">
                <h:outputText value="Participante já cadastrado." />
            </p:dialog>
            <p:dialog id="alerta2" header="Erro!" binding="#{participanteBean.alerta2}" class="alerta">
                <h:outputText value="O campo CPF não pode ser vazio." />
            </p:dialog>
            <ui:include src="footer.xhtml"></ui:include>
        </div>
    </h:body>
</xhtml>